services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    volumes:
      - lc8-postgres-data:/var/lib/postgresql/data

volumes:
  lc8-postgres-data:
